#!/bin/bash


# Documentation: https://gkarthiks.github.io/quick-commands-cheat-sheet/bash_command.html

Black=''
DarkGray=''
LightGray=''
Red=''
LightRed=''
Green=''
LightGreen=''
Brown=''
Yellow=''
Blue=''
LightBlue=''
Purple=''
LightPurple=''
Cyan=''
LightCyan=''
White=''

